services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    expose:
      - '5432'
    ports:
      - '5433:5432'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
