DROP TABLE IF EXISTS users, coordinates, address, organization CASCADE;
DROP TYPE IF EXISTS organization_type CASCADE ;
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL
);

CREATE TABLE coordinates (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY
         PRIMARY KEY,
     x DOUBLE PRECISION NOT NULL,
     y DOUBLE PRECISION NOT NULL CHECK (y > -162)
);

CREATE TABLE address (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY
         PRIMARY KEY,
     street TEXT NOT NULL CHECK (length(street) > 0),
     zipcode TEXT NOT NULL
);

CREATE TABLE organization (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY
           PRIMARY KEY,
       name TEXT NOT NULL CHECK (length(name) > 0),
       coordinates_id BIGINT REFERENCES coordinates(id)  ON DELETE CASCADE NOT NULL,
       local_date DATE DEFAULT NOW(),
       annual_turnover BIGINT NOT NULL CHECK (annual_turnover > 0),
       full_name TEXT CHECK (length(full_name) <= 1311),
       employees_count BIGINT NOT NULL CHECK (employees_count > 0),
       organization_type VARCHAR(32) NOT NULL,
       address_id BIGINT REFERENCES address(id) ON DELETE CASCADE NOT NULL,

       creator_id BIGINT REFERENCES users(id) NOT NULL
);